### ISSUE TITLE
Bug with add button if I submit empty string

### ISSUE THREAD

**Issue by modestfake** [mYokha/react-introduction-app#2]
The bug is present in this [PR](https://github.com/mYokha/react-introduction-app/pull/1).

When I submit an empty input the sum from state turns into `string`. And then if type any number and submit it, numbers just concating.
![image](https://user-images.githubusercontent.com/16977959/29328072-e0f7cf34-81f9-11e7-92c5-a6e37e09d264.png)

## Reproduce steps:
1. Click Add button.
2. Type any number and click the button again.

### Behavior:
'' + 5 + 3 = 350

### Expected behavior:
'' + 5 + 3 = 8

## Proposal:
Disable the button if input value length is 0.

**Comment by myokha** [comment]
done
